# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

    hostname = "win.rustbox"
    locale = "en_GB.UTF.8"

    config.vm.box = "peru/windows-10-enterprise-x64-eval"

    config.vm.provider "libvirt" do |v|
        v.graphics_type = "vnc"
        v.graphics_autoport = true
        v.memory = 4096
        v.cpus = 2
    end
    
    config.vm.provision "shell", inline: <<-SHELL
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        
        # upgrade choco
        choco upgrade chocolatey -y

        choco config set commandExecutionTimeoutSeconds 2700

        # dev tools
        $ErrorActionPreference = 'Stop'
        $maxRetries = 3
        $retryCount = 0
        while ($retryCount -lt $maxRetries) {
            try {
                choco install git -y
                choco install rust -y
                choco install thorium -y # use this to install discord-ptb
                choco install imhex -y
                break
            } catch {
                Write-Host "Installation failed, retrying..."
                $retryCount++
                Start-Sleep -Seconds 10
            }
        }
        
        # clone repo
        cd C:\\Users\\vagrant\\Desktop
        try {
            git clone https://github.com/0xSolanaceae/discord-imhex.git
        } catch {
            Write-Host "clone failed, continuing..."
        }
    SHELL
end